export const USER = {
  USERNAME: 'demo@cinemo.com',
  PASSWORD: 'demo1234',
}

export const STATUS_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_Forbidden: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_CONFLICT: 409,
  ERROR_API: 500,
}
